### ISSUE TITLE
[BUG] - Enter a descriptive title

### ISSUE THREAD

**Issue by jakesyl** [vultr/vultr-csi#25]
**Describe the bug**

![Screen Shot 2020-04-28 at 6 56 05 AM](https://user-images.githubusercontent.com/6392429/80479929-cdeade80-891d-11ea-9036-b6d331a51d44.png)
![Screen Shot 2020-04-28 at 6 55 47 AM](https://user-images.githubusercontent.com/6392429/80479933-cfb4a200-891d-11ea-9137-62062d87018a.png)
![Screen Shot 2020-04-28 at 6 55 14 AM](https://user-images.githubusercontent.com/6392429/80479937-d0e5cf00-891d-11ea-96d2-ebc441393927.png)

**To Reproduce**
1. Create a kubernetes cluster:
1. `kubectl apply -f https://raw.githubusercontent.com/vultr/vultr-csi/master/docs/releases/latest.yml`

**Expected behavior**

No errors

**Comment by ddymko** [comment]
The issue here is your instances nodeName (which is passed in by kubernetes) is `8.9.31.83` and the CSI can not find any instances on your account with a label of `8.9.31.83`.

Currently when you deploy an instance on vultr.com and you supply a hostname this will also be the instances label (unless you change it). This causes a problem if you deploy a instance without a hostname since it will default to the IP address. To fix this you can assign your instance the label of `8.9.31.83`.

In v0.0.2 we will change this initial behavior to pull information from the instances metadata.

**Comment by jakesyl** [comment]
Got it - thanks for the reply @ddymko
